image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run
  - name: Debug
    command: dotnet build /workspace/template-dotnet-core-cli-csharp/dotnetcore.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 

vscode:
  extensions:
    - muhammad-sammy.csharp
